export enum PATHS {
  ROOT = '/',
  HOME = 'main',
  AUTH = '/auth',
  MENU = '/menu',
  SUNRISE_SPECIALS = 'sunriseSpecials',
  CULINARY_CLASSICS = 'culinaryClassics',
  BAR_BLISS = 'barBliss',
  CHEFS_PICK = 'chefsPick',
  MENU_ITEM = '/menu:id',
  CART = '/cart',
  ACCOUNT = '/account',
  USER_INFO = 'userInfoForm',
  DELIVERY_ADDRESS = 'deliveryAddress',
  PAYMENT = 'payment',
  CHECKOUT = '/checkout',
  BOOK_TABLE = 'booktable',
  DELIVERY = 'delivery',
  TAKEOUT = 'takeout',
  ORDER_PAYMENT = 'orderPayment',
  ORDER_CONFIRMATION = 'confirmation',
  ORDERS = '/orders',
  ERROR = '*',
}
