export enum PATHS {
  ROOT = "/",
  HOME = "main",
  AUTH = "/auth",
  MENU = "/menu",
  MENU_ITEM = "/menu:id",
  CART = "/cart",
  ACCOUNT = "/account",
  USER_INFO = "userInfoForm",
  DELIVERY_ADDRESS = "deliveryAddress",
  PAYMENT = "payment",
  CHECKOUT = "/checkout",
  BOOK_TABLE = "booktable",
  DELIVERY = "delivery",
  TAKEOUT = "takeout",
  ORDER_PAYMENT = "orderPayment",
  ORDER_CONFIRMATION = "confirmation",
  ORDERS = "/orders",
  ERROR = "*"
}
