export enum PATHS {
  ROOT = "/",
  HOME = "main",
  AUTH = "/auth",
  MENU = "/menu",
  MENUITEM = "/menu:id",
  CART = "/cart",
  ACCOUNT = "/account",
  USER_INFO = "account/userInfoForm",
  DELIVERY_ADDRESS = "account/deliveryAddress",
  PAYMENT = "account/payment",
  CHECKOUT = "/checkout",
  BOOK_TABLE = "/checkout/booktable",
  DELIVERY = "checkout/delivery",
  TAKEOUT = "checkout/takeout",
  ORDER_PAYMENT = "checkout/payment",
  ORDER_CONFIRMATION = "checkout/confirmation",
  ORDERS = "/orders",
  ERROR = "*"
}
